# Generated by Django 3.0.2 on 2020-02-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivity', '0002_auto_20200205_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
