# Generated by Django 3.0.2 on 2020-02-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivity', '0003_auto_20200205_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cleaner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
