# Generated by Django 3.0.2 on 2020-02-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='timeslot',
            field=models.IntegerField(choices=[('1', '10 AM - 12 PM'), ('2', '12 PM - 02 PM'), ('3', '02 PM - 04 PM'), ('4', '04 PM - 06 PM'), ('5', '06 PM - 08 PM')]),
        ),
    ]
