# Generated by Django 3.0.2 on 2020-02-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200206_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='dateofcleaning',
            field=models.DateField(verbose_name='Date Of Cleaning'),
        ),
    ]
